### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by kk94wang** [BobMcDear/NN_CUDA#1]
This might be a stupid question, but how to compile and run the code? 
Thank you!

**Comment by BobMcDear** [comment]
@kk94wang Apologies for the late response. 

No, it's by no means a stupid question. Supposing your system has the Nvidia CUDA Compiler (NVCC), compiling a ```.cu``` program is done through running ```nvcc filename.cu dependencies.cu dependencies.cpp```. Here, the dependencies refer to external files utilized by ```filename.cu```. For instance, assume you would like to compile ```test/linear.cu```; that program uses ```CPU/linear.cpp```, ```GPU/linear.cu```, and ```utils/utils.cpp```, thus you would command ```nvcc test/linear.cu CPU/linear.cpp GPU/linear.cu utils/utils.cpp```. This creates ```a.out```, which may be executed via ```./a.out```. 

Does that answer your question?

**Comment by kk94wang** [comment]
Yes, that helps!
Thank you very much!

**Comment by kk94wang** [comment]
> @kk94wang Apologies for the late response.
> 
> No, it's by no means a stupid question. Supposing your system has the Nvidia CUDA Compiler (NVCC), compiling a `.cu` program is done through running `nvcc filename.cu dependencies.cu dependencies.cpp`. Here, the dependencies refer to external files utilized by `filename.cu`. For instance, assume you would like to compile `test/linear.cu`; that program uses `CPU/linear.cpp`, `GPU/linear.cu`, and `utils/utils.cpp`, thus you would command `nvcc test/linear.cu CPU/linear.cpp GPU/linear.cu utils/utils.cpp`. This creates `a.out`, which may be executed via `./a.out`.
> 
> Does that answer your question?

Yes, that helps!
Thank you very much!

**Comment by Minay98** [comment]
what's the command ‌to run main.cu?
Does it run just on the GPU?"
