### ISSUE TITLE
Using less data

### ISSUE THREAD

**Issue by yy1401** [BobMcDear/NN_CUDA#3]
Hello,

I was wondering if it would be possible to use the code with fewer data samples? For example, currently there are 100,000 rows, but would it be possible to train only on 10,000 data points?

Thank you!

**Comment by BobMcDear** [comment]
Hello,

Yes, that should be easy. You could simply delete however many data points you do not need from the CSV files and adjust the batch size in the training script accordingly.

Please let me know if this answers your question.

**Comment by yy1401** [comment]
That's very helpful, thanks again!
